// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reads.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Reads_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Reads_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Reads_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Reads_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Reads_2eproto;
namespace goby {
class MetaData;
class MetaDataDefaultTypeInternal;
extern MetaDataDefaultTypeInternal _MetaData_default_instance_;
class ReadCollection;
class ReadCollectionDefaultTypeInternal;
extern ReadCollectionDefaultTypeInternal _ReadCollection_default_instance_;
class ReadEntry;
class ReadEntryDefaultTypeInternal;
extern ReadEntryDefaultTypeInternal _ReadEntry_default_instance_;
}  // namespace goby
PROTOBUF_NAMESPACE_OPEN
template<> ::goby::MetaData* Arena::CreateMaybeMessage<::goby::MetaData>(Arena*);
template<> ::goby::ReadCollection* Arena::CreateMaybeMessage<::goby::ReadCollection>(Arena*);
template<> ::goby::ReadEntry* Arena::CreateMaybeMessage<::goby::ReadEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace goby {

// ===================================================================

class ReadCollection :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:goby.ReadCollection) */ {
 public:
  ReadCollection();
  virtual ~ReadCollection();

  ReadCollection(const ReadCollection& from);
  ReadCollection(ReadCollection&& from) noexcept
    : ReadCollection() {
    *this = ::std::move(from);
  }

  inline ReadCollection& operator=(const ReadCollection& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadCollection& operator=(ReadCollection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadCollection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadCollection* internal_default_instance() {
    return reinterpret_cast<const ReadCollection*>(
               &_ReadCollection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReadCollection* other);
  friend void swap(ReadCollection& a, ReadCollection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReadCollection* New() const final {
    return CreateMaybeMessage<ReadCollection>(nullptr);
  }

  ReadCollection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadCollection>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadCollection& from);
  void MergeFrom(const ReadCollection& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadCollection* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "goby.ReadCollection";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Reads_2eproto);
    return ::descriptor_table_Reads_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .goby.ReadEntry reads = 1;
  int reads_size() const;
  void clear_reads();
  static const int kReadsFieldNumber = 1;
  ::goby::ReadEntry* mutable_reads(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::ReadEntry >*
      mutable_reads();
  const ::goby::ReadEntry& reads(int index) const;
  ::goby::ReadEntry* add_reads();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::ReadEntry >&
      reads() const;

  // @@protoc_insertion_point(class_scope:goby.ReadCollection)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::ReadEntry > reads_;
  friend struct ::TableStruct_Reads_2eproto;
};
// -------------------------------------------------------------------

class ReadEntry :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:goby.ReadEntry) */ {
 public:
  ReadEntry();
  virtual ~ReadEntry();

  ReadEntry(const ReadEntry& from);
  ReadEntry(ReadEntry&& from) noexcept
    : ReadEntry() {
    *this = ::std::move(from);
  }

  inline ReadEntry& operator=(const ReadEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadEntry& operator=(ReadEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadEntry* internal_default_instance() {
    return reinterpret_cast<const ReadEntry*>(
               &_ReadEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ReadEntry* other);
  friend void swap(ReadEntry& a, ReadEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReadEntry* New() const final {
    return CreateMaybeMessage<ReadEntry>(nullptr);
  }

  ReadEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadEntry>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadEntry& from);
  void MergeFrom(const ReadEntry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadEntry* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "goby.ReadEntry";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Reads_2eproto);
    return ::descriptor_table_Reads_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .goby.MetaData meta_data = 25;
  int meta_data_size() const;
  void clear_meta_data();
  static const int kMetaDataFieldNumber = 25;
  ::goby::MetaData* mutable_meta_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::MetaData >*
      mutable_meta_data();
  const ::goby::MetaData& meta_data(int index) const;
  ::goby::MetaData* add_meta_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::MetaData >&
      meta_data() const;

  // optional bytes sequence = 3;
  bool has_sequence() const;
  void clear_sequence();
  static const int kSequenceFieldNumber = 3;
  const std::string& sequence() const;
  void set_sequence(const std::string& value);
  void set_sequence(std::string&& value);
  void set_sequence(const char* value);
  void set_sequence(const void* value, size_t size);
  std::string* mutable_sequence();
  std::string* release_sequence();
  void set_allocated_sequence(std::string* sequence);

  // optional bytes quality_scores = 4;
  bool has_quality_scores() const;
  void clear_quality_scores();
  static const int kQualityScoresFieldNumber = 4;
  const std::string& quality_scores() const;
  void set_quality_scores(const std::string& value);
  void set_quality_scores(std::string&& value);
  void set_quality_scores(const char* value);
  void set_quality_scores(const void* value, size_t size);
  std::string* mutable_quality_scores();
  std::string* release_quality_scores();
  void set_allocated_quality_scores(std::string* quality_scores);

  // optional bytes sequence_pair = 5;
  bool has_sequence_pair() const;
  void clear_sequence_pair();
  static const int kSequencePairFieldNumber = 5;
  const std::string& sequence_pair() const;
  void set_sequence_pair(const std::string& value);
  void set_sequence_pair(std::string&& value);
  void set_sequence_pair(const char* value);
  void set_sequence_pair(const void* value, size_t size);
  std::string* mutable_sequence_pair();
  std::string* release_sequence_pair();
  void set_allocated_sequence_pair(std::string* sequence_pair);

  // optional bytes quality_scores_pair = 7;
  bool has_quality_scores_pair() const;
  void clear_quality_scores_pair();
  static const int kQualityScoresPairFieldNumber = 7;
  const std::string& quality_scores_pair() const;
  void set_quality_scores_pair(const std::string& value);
  void set_quality_scores_pair(std::string&& value);
  void set_quality_scores_pair(const char* value);
  void set_quality_scores_pair(const void* value, size_t size);
  std::string* mutable_quality_scores_pair();
  std::string* release_quality_scores_pair();
  void set_allocated_quality_scores_pair(std::string* quality_scores_pair);

  // optional bytes compressed_data = 8;
  bool has_compressed_data() const;
  void clear_compressed_data();
  static const int kCompressedDataFieldNumber = 8;
  const std::string& compressed_data() const;
  void set_compressed_data(const std::string& value);
  void set_compressed_data(std::string&& value);
  void set_compressed_data(const char* value);
  void set_compressed_data(const void* value, size_t size);
  std::string* mutable_compressed_data();
  std::string* release_compressed_data();
  void set_allocated_compressed_data(std::string* compressed_data);

  // optional string description = 22;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 22;
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);

  // optional string read_identifier = 23;
  bool has_read_identifier() const;
  void clear_read_identifier();
  static const int kReadIdentifierFieldNumber = 23;
  const std::string& read_identifier() const;
  void set_read_identifier(const std::string& value);
  void set_read_identifier(std::string&& value);
  void set_read_identifier(const char* value);
  void set_read_identifier(const char* value, size_t size);
  std::string* mutable_read_identifier();
  std::string* release_read_identifier();
  void set_allocated_read_identifier(std::string* read_identifier);

  // required uint32 read_index = 1;
  bool has_read_index() const;
  void clear_read_index();
  static const int kReadIndexFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 read_index() const;
  void set_read_index(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // required uint32 read_length = 2;
  bool has_read_length() const;
  void clear_read_length();
  static const int kReadLengthFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint32 read_length() const;
  void set_read_length(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // optional uint32 read_length_pair = 6;
  bool has_read_length_pair() const;
  void clear_read_length_pair();
  static const int kReadLengthPairFieldNumber = 6;
  ::PROTOBUF_NAMESPACE_ID::uint32 read_length_pair() const;
  void set_read_length_pair(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // optional uint32 barcode_index = 10;
  bool has_barcode_index() const;
  void clear_barcode_index();
  static const int kBarcodeIndexFieldNumber = 10;
  ::PROTOBUF_NAMESPACE_ID::uint32 barcode_index() const;
  void set_barcode_index(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:goby.ReadEntry)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::MetaData > meta_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sequence_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr quality_scores_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sequence_pair_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr quality_scores_pair_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compressed_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr read_identifier_;
  ::PROTOBUF_NAMESPACE_ID::uint32 read_index_;
  ::PROTOBUF_NAMESPACE_ID::uint32 read_length_;
  ::PROTOBUF_NAMESPACE_ID::uint32 read_length_pair_;
  ::PROTOBUF_NAMESPACE_ID::uint32 barcode_index_;
  friend struct ::TableStruct_Reads_2eproto;
};
// -------------------------------------------------------------------

class MetaData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:goby.MetaData) */ {
 public:
  MetaData();
  virtual ~MetaData();

  MetaData(const MetaData& from);
  MetaData(MetaData&& from) noexcept
    : MetaData() {
    *this = ::std::move(from);
  }

  inline MetaData& operator=(const MetaData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetaData& operator=(MetaData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MetaData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MetaData* internal_default_instance() {
    return reinterpret_cast<const MetaData*>(
               &_MetaData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(MetaData* other);
  friend void swap(MetaData& a, MetaData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MetaData* New() const final {
    return CreateMaybeMessage<MetaData>(nullptr);
  }

  MetaData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MetaData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MetaData& from);
  void MergeFrom(const MetaData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MetaData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "goby.MetaData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Reads_2eproto);
    return ::descriptor_table_Reads_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const std::string& key() const;
  void set_key(const std::string& value);
  void set_key(std::string&& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  std::string* mutable_key();
  std::string* release_key();
  void set_allocated_key(std::string* key);

  // required string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);

  // @@protoc_insertion_point(class_scope:goby.MetaData)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  friend struct ::TableStruct_Reads_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReadCollection

// repeated .goby.ReadEntry reads = 1;
inline int ReadCollection::reads_size() const {
  return reads_.size();
}
inline void ReadCollection::clear_reads() {
  reads_.Clear();
}
inline ::goby::ReadEntry* ReadCollection::mutable_reads(int index) {
  // @@protoc_insertion_point(field_mutable:goby.ReadCollection.reads)
  return reads_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::ReadEntry >*
ReadCollection::mutable_reads() {
  // @@protoc_insertion_point(field_mutable_list:goby.ReadCollection.reads)
  return &reads_;
}
inline const ::goby::ReadEntry& ReadCollection::reads(int index) const {
  // @@protoc_insertion_point(field_get:goby.ReadCollection.reads)
  return reads_.Get(index);
}
inline ::goby::ReadEntry* ReadCollection::add_reads() {
  // @@protoc_insertion_point(field_add:goby.ReadCollection.reads)
  return reads_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::ReadEntry >&
ReadCollection::reads() const {
  // @@protoc_insertion_point(field_list:goby.ReadCollection.reads)
  return reads_;
}

// -------------------------------------------------------------------

// ReadEntry

// required uint32 read_index = 1;
inline bool ReadEntry::has_read_index() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ReadEntry::clear_read_index() {
  read_index_ = 0u;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReadEntry::read_index() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_index)
  return read_index_;
}
inline void ReadEntry::set_read_index(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000080u;
  read_index_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_index)
}

// optional uint32 barcode_index = 10;
inline bool ReadEntry::has_barcode_index() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void ReadEntry::clear_barcode_index() {
  barcode_index_ = 0u;
  _has_bits_[0] &= ~0x00000400u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReadEntry::barcode_index() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.barcode_index)
  return barcode_index_;
}
inline void ReadEntry::set_barcode_index(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000400u;
  barcode_index_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.barcode_index)
}

// optional string read_identifier = 23;
inline bool ReadEntry::has_read_identifier() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ReadEntry::clear_read_identifier() {
  read_identifier_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000040u;
}
inline const std::string& ReadEntry::read_identifier() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_identifier)
  return read_identifier_.GetNoArena();
}
inline void ReadEntry::set_read_identifier(const std::string& value) {
  _has_bits_[0] |= 0x00000040u;
  read_identifier_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_identifier)
}
inline void ReadEntry::set_read_identifier(std::string&& value) {
  _has_bits_[0] |= 0x00000040u;
  read_identifier_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.ReadEntry.read_identifier)
}
inline void ReadEntry::set_read_identifier(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000040u;
  read_identifier_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.read_identifier)
}
inline void ReadEntry::set_read_identifier(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000040u;
  read_identifier_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.read_identifier)
}
inline std::string* ReadEntry::mutable_read_identifier() {
  _has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.read_identifier)
  return read_identifier_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReadEntry::release_read_identifier() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.read_identifier)
  if (!has_read_identifier()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000040u;
  return read_identifier_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_read_identifier(std::string* read_identifier) {
  if (read_identifier != nullptr) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  read_identifier_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), read_identifier);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.read_identifier)
}

// optional string description = 22;
inline bool ReadEntry::has_description() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ReadEntry::clear_description() {
  description_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ReadEntry::description() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.description)
  return description_.GetNoArena();
}
inline void ReadEntry::set_description(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.description)
}
inline void ReadEntry::set_description(std::string&& value) {
  _has_bits_[0] |= 0x00000020u;
  description_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.ReadEntry.description)
}
inline void ReadEntry::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000020u;
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.description)
}
inline void ReadEntry::set_description(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000020u;
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.description)
}
inline std::string* ReadEntry::mutable_description() {
  _has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.description)
  return description_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReadEntry::release_description() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.description)
  if (!has_description()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return description_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  description_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.description)
}

// required uint32 read_length = 2;
inline bool ReadEntry::has_read_length() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ReadEntry::clear_read_length() {
  read_length_ = 0u;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReadEntry::read_length() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_length)
  return read_length_;
}
inline void ReadEntry::set_read_length(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000100u;
  read_length_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_length)
}

// optional bytes sequence = 3;
inline bool ReadEntry::has_sequence() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReadEntry::clear_sequence() {
  sequence_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ReadEntry::sequence() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.sequence)
  return sequence_.GetNoArena();
}
inline void ReadEntry::set_sequence(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  sequence_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.sequence)
}
inline void ReadEntry::set_sequence(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  sequence_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.ReadEntry.sequence)
}
inline void ReadEntry::set_sequence(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  sequence_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.sequence)
}
inline void ReadEntry::set_sequence(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  sequence_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.sequence)
}
inline std::string* ReadEntry::mutable_sequence() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.sequence)
  return sequence_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReadEntry::release_sequence() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.sequence)
  if (!has_sequence()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return sequence_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_sequence(std::string* sequence) {
  if (sequence != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  sequence_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sequence);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.sequence)
}

// optional bytes sequence_pair = 5;
inline bool ReadEntry::has_sequence_pair() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReadEntry::clear_sequence_pair() {
  sequence_pair_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ReadEntry::sequence_pair() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.sequence_pair)
  return sequence_pair_.GetNoArena();
}
inline void ReadEntry::set_sequence_pair(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  sequence_pair_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.sequence_pair)
}
inline void ReadEntry::set_sequence_pair(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  sequence_pair_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.ReadEntry.sequence_pair)
}
inline void ReadEntry::set_sequence_pair(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  sequence_pair_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.sequence_pair)
}
inline void ReadEntry::set_sequence_pair(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  sequence_pair_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.sequence_pair)
}
inline std::string* ReadEntry::mutable_sequence_pair() {
  _has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.sequence_pair)
  return sequence_pair_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReadEntry::release_sequence_pair() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.sequence_pair)
  if (!has_sequence_pair()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return sequence_pair_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_sequence_pair(std::string* sequence_pair) {
  if (sequence_pair != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  sequence_pair_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sequence_pair);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.sequence_pair)
}

// optional uint32 read_length_pair = 6;
inline bool ReadEntry::has_read_length_pair() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ReadEntry::clear_read_length_pair() {
  read_length_pair_ = 0u;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReadEntry::read_length_pair() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_length_pair)
  return read_length_pair_;
}
inline void ReadEntry::set_read_length_pair(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000200u;
  read_length_pair_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_length_pair)
}

// optional bytes quality_scores = 4;
inline bool ReadEntry::has_quality_scores() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReadEntry::clear_quality_scores() {
  quality_scores_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ReadEntry::quality_scores() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.quality_scores)
  return quality_scores_.GetNoArena();
}
inline void ReadEntry::set_quality_scores(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  quality_scores_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.quality_scores)
}
inline void ReadEntry::set_quality_scores(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  quality_scores_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.ReadEntry.quality_scores)
}
inline void ReadEntry::set_quality_scores(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  quality_scores_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.quality_scores)
}
inline void ReadEntry::set_quality_scores(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  quality_scores_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.quality_scores)
}
inline std::string* ReadEntry::mutable_quality_scores() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.quality_scores)
  return quality_scores_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReadEntry::release_quality_scores() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.quality_scores)
  if (!has_quality_scores()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return quality_scores_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_quality_scores(std::string* quality_scores) {
  if (quality_scores != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  quality_scores_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), quality_scores);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.quality_scores)
}

// optional bytes quality_scores_pair = 7;
inline bool ReadEntry::has_quality_scores_pair() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ReadEntry::clear_quality_scores_pair() {
  quality_scores_pair_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ReadEntry::quality_scores_pair() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.quality_scores_pair)
  return quality_scores_pair_.GetNoArena();
}
inline void ReadEntry::set_quality_scores_pair(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  quality_scores_pair_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.quality_scores_pair)
}
inline void ReadEntry::set_quality_scores_pair(std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  quality_scores_pair_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.ReadEntry.quality_scores_pair)
}
inline void ReadEntry::set_quality_scores_pair(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  quality_scores_pair_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.quality_scores_pair)
}
inline void ReadEntry::set_quality_scores_pair(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000008u;
  quality_scores_pair_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.quality_scores_pair)
}
inline std::string* ReadEntry::mutable_quality_scores_pair() {
  _has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.quality_scores_pair)
  return quality_scores_pair_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReadEntry::release_quality_scores_pair() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.quality_scores_pair)
  if (!has_quality_scores_pair()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return quality_scores_pair_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_quality_scores_pair(std::string* quality_scores_pair) {
  if (quality_scores_pair != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  quality_scores_pair_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), quality_scores_pair);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.quality_scores_pair)
}

// optional bytes compressed_data = 8;
inline bool ReadEntry::has_compressed_data() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ReadEntry::clear_compressed_data() {
  compressed_data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ReadEntry::compressed_data() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.compressed_data)
  return compressed_data_.GetNoArena();
}
inline void ReadEntry::set_compressed_data(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  compressed_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.compressed_data)
}
inline void ReadEntry::set_compressed_data(std::string&& value) {
  _has_bits_[0] |= 0x00000010u;
  compressed_data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.ReadEntry.compressed_data)
}
inline void ReadEntry::set_compressed_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000010u;
  compressed_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.compressed_data)
}
inline void ReadEntry::set_compressed_data(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000010u;
  compressed_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.compressed_data)
}
inline std::string* ReadEntry::mutable_compressed_data() {
  _has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.compressed_data)
  return compressed_data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReadEntry::release_compressed_data() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.compressed_data)
  if (!has_compressed_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return compressed_data_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_compressed_data(std::string* compressed_data) {
  if (compressed_data != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  compressed_data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), compressed_data);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.compressed_data)
}

// repeated .goby.MetaData meta_data = 25;
inline int ReadEntry::meta_data_size() const {
  return meta_data_.size();
}
inline void ReadEntry::clear_meta_data() {
  meta_data_.Clear();
}
inline ::goby::MetaData* ReadEntry::mutable_meta_data(int index) {
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.meta_data)
  return meta_data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::MetaData >*
ReadEntry::mutable_meta_data() {
  // @@protoc_insertion_point(field_mutable_list:goby.ReadEntry.meta_data)
  return &meta_data_;
}
inline const ::goby::MetaData& ReadEntry::meta_data(int index) const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.meta_data)
  return meta_data_.Get(index);
}
inline ::goby::MetaData* ReadEntry::add_meta_data() {
  // @@protoc_insertion_point(field_add:goby.ReadEntry.meta_data)
  return meta_data_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::goby::MetaData >&
ReadEntry::meta_data() const {
  // @@protoc_insertion_point(field_list:goby.ReadEntry.meta_data)
  return meta_data_;
}

// -------------------------------------------------------------------

// MetaData

// required string key = 1;
inline bool MetaData::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MetaData::clear_key() {
  key_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MetaData::key() const {
  // @@protoc_insertion_point(field_get:goby.MetaData.key)
  return key_.GetNoArena();
}
inline void MetaData::set_key(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.MetaData.key)
}
inline void MetaData::set_key(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  key_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.MetaData.key)
}
inline void MetaData::set_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.MetaData.key)
}
inline void MetaData::set_key(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.MetaData.key)
}
inline std::string* MetaData::mutable_key() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:goby.MetaData.key)
  return key_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MetaData::release_key() {
  // @@protoc_insertion_point(field_release:goby.MetaData.key)
  if (!has_key()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return key_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MetaData::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  key_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:goby.MetaData.key)
}

// required string value = 2;
inline bool MetaData::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MetaData::clear_value() {
  value_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& MetaData::value() const {
  // @@protoc_insertion_point(field_get:goby.MetaData.value)
  return value_.GetNoArena();
}
inline void MetaData::set_value(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.MetaData.value)
}
inline void MetaData::set_value(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:goby.MetaData.value)
}
inline void MetaData::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.MetaData.value)
}
inline void MetaData::set_value(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.MetaData.value)
}
inline std::string* MetaData::mutable_value() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:goby.MetaData.value)
  return value_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MetaData::release_value() {
  // @@protoc_insertion_point(field_release:goby.MetaData.value)
  if (!has_value()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return value_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MetaData::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  value_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:goby.MetaData.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace goby

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Reads_2eproto
